
version: "3" 

services: 

  nifi: 

    image: "apache/nifi:latest"
    container_name: nifi
    ports: 

      - "8443:8443" #HTTPS Port
      - 1433
      - 1434

    environment: 

      - NIFI_WEB_HTTPS_PORT=8443 

      - SINGLE_USER_CREDENTIALS_USERNAME:${USER_ACCESS}

      - SINGLE_USER_CREDENTIALS_PASSWORD:${USER_PASS}

      - NIFI_WEB_PROXY_HOST=10.30.15.246:8443

    networks:

      - my-net-sql

networks:

  my-net-sql:

    external: true
